161 contract for simple staking
GoodDollar/GoodContracts pull request #174
Opened 2020-06-30 15:21 UTC by PremSOMISH

# Description

Contract for SimpleStaking. This is common generic contract for staking, its code will be unchanged for any protocol. So same code will be used for any defi protocol.
About #161

# How Has This Been Tested?

It is not tested yet. It will be tested in #163.

2020-06-30 18:46 UTC, sirpy requested changes

2020-06-30 18:46 UTC, sirpy commented on stakingModel/contracts/SimpleStaking.sol
> +        uint256 er = exchangeRate();
i dont think its possible. to use exchangeRate that will be defined in a child contract ie in GoodCompoundStaking

2020-07-01 13:50 UTC, PremSOMISH commented on stakingModel/contracts/SimpleStaking.sol
> +        uint256 er = exchangeRate();
Hi @sirpy , I believe this should work. My approach is that we only deploy child contracts like GoodCompoundStaking contract and never deploy parent contract SimpleStaking directly. Tomorrow if we wish to introduce a new DeFi protocol eg:- Aave, we can very quickly deploy GoodAaveStaking reusing the entire code of SimpleStaking and only writing functions specific to Aave protocol. Let  me know if this makes sense.

2020-07-02 12:50 UTC, sirpy approved these changes

2020-07-02 13:22 UTC, merged